version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
      - "4173:4173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
